routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/test', function () {
    
});

Auth::routes();

Route::get('/', 'DashboardController@index')->name('dashboard');
Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('products','ProductController');
    Route::resource('pasiens','PasienController');
    Route::get('/laporan', 'LaporanController@index');
    Route::get('/laporan/10penyakit/{from}/{to}', 'LaporanController@penyakitterbesar');
});

app/Models/Pasien.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Pasien extends Model
{
    //
    protected $table = 'tbl_master_pasien';

}

app/Http/Controllers/PasienController.php
<?php

namespace App\Http\Controllers;

use App\Models\Pasien;
use Illuminate\Http\Request;

class PasienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:pasien-list');
         $this->middleware('permission:pasien-create', ['only' => ['create','store']]);
         $this->middleware('permission:pasien-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:pasien-delete', ['only' => ['destroy']]);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pasiens = Pasien::latest()->paginate(5);
        return view('pasiens.index',compact('pasiens'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('pasiens.create');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);


        Product::create($request->all());


        return redirect()->route('products.index')
                        ->with('success','Product created successfully.');
    }


    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        return view('products.show',compact('product'));
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        return view('products.edit',compact('product'));
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Product $product)
    {
         request()->validate([
            'name' => 'required',
            'detail' => 'required',
        ]);


        $product->update($request->all());


        return redirect()->route('products.index')
                        ->with('success','Product updated successfully');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();


        return redirect()->route('products.index')
                        ->with('success','Product deleted successfully');
    }
}

resources/views/pasiens/index.blade.php
@extends('layout.master')
@section('navbrand')
    <a class="navbar-brand" href="#">Master Pasien</a>
@endsection
@section('btnSreach')
    <form class="navbar-form">
        <div class="input-group no-border">
            <input type="text" value="" class="form-control" placeholder="Search...">
            <button type="submit" class="btn btn-white btn-round btn-just-icon">
                <i class="material-icons">search</i>
                <div class="ripple-container"></div>
            </button>
        </div>
    </form>
@endsection
@section('content')
        <div class="row">
            <div class="col-md-12">
            @if ($message = Session::get('success'))
                <div class="alert alert-success">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <i class="material-icons">close</i>
                    </button>
                    <span>{{ $message }}</span>
                </div>
            @endif
                <div class="card">
                    <div class="card-header card-header-rose card-header-icon">
                    <div class="card-icon">
                        <i class="material-icons">assignment</i>
                    </div>
                    <h4 class="card-title">Tabel Pasien
                        <div class="pull-right">
                        @can('pasien-create')
                            <a class="btn btn-success" href="{{ route('pasiens.create') }}"> Pasien Baru</a>
                            @endcan
                        </div>
                    </h4>
                    </div>
                    <div class="card-body">
                    <div class="table-responsive">
                        <table class="table">
                        <thead>
                            <tr>
                            <th class="text-center">#</th>
                            <th>ID</th>
                            <th>Nama pasien</th>
                            <th class="text-right">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($pasiens as $key => $pasien)
                            <tr>
                                <td  class="text-center">{{ ++$i }}</td>
                                <td>{{ $pasien->id }}</td>
                                <td>{{ $pasien->nama }}</td>
                                <td class="td-actions text-right">
                                    <a class="btn btn-info" href="{{ route('pasiens.show',$pasien->id) }}">
                                        <i class="material-icons">visibility</i>
                                    </a>
                                    @can('pasien-edit')
                                        <a class="btn btn-primary" href="{{ route('pasiens.edit',$pasien->id) }}">
                                            <i class="material-icons">edit</i>
                                        </a>
                                    @endcan
                                    @can('pasien-delete')
                                        {!! Form::open(['method' => 'DELETE','route' => ['pasiens.destroy', $pasien->id],'style'=>'display:inline']) !!}
                                            {!! Form::button('<i class="material-icons">close</i>',['type'=>'submit','class' => 'btn btn-danger']) !!}
                                        {!! Form::close() !!}
                                    @endcan
                                </td>
                            </tr>
                            @endforeach
                            
                        </tbody>
                        </table>
                    </div>
                    </div>
                </div>
            </div>
            <!-- kalo nak nambah tabel lain pake 'col-md-12' -->
        </div>

{!! $pasiens->render() !!}


@endsection